image: 10.18.17.26:5005/root/my_site_upgrade:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

stages:
  - backup
  - deploy
  - testing

backup:
  stage: backup
  script: 
  - ssh -o StrictHostKeyChecking=no $SITE_VM "gzip /home/yaroslav/html/helloworld.html" 
  only:
  - master

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $SITE_VM "rm -f /home/yaroslav/html/helloworld.html"
    - scp -o StrictHostKeyChecking=no helloworld.html $SITE_VM:/home/yaroslav/html
  only:
  - master
  
test page:
  stage: testing
  script: 
    - CURL=$(curl -isS http://10.18.17.25 | head -1 | awk {'print $2'})
    - "if [ \"$CURL\" != 200 ]; then exit 1; else exit 0; fi"
  only:
  - master
